from array_api import Array

objectArray = Array(); 'creating an object array'

'here I will do all the work'

print(0, ':CREATE,')
objectArray.debug_print()
objectArray.add('a')
objectArray.add('e')
objectArray.add('r')
objectArray.add('o')
objectArray.add('l')
objectArray.add('o')
objectArray.add('d')
objectArray.add('u')
objectArray.add('s')
objectArray.add('a')
objectArray.debug_print()
objectArray.add('u')
objectArray.debug_print()
objectArray.set(4,'S')
objectArray.set(12,'M')
objectArray.debug_print()
objectArray.get(8)
objectArray.get(11)
objectArray.insert(21, 'b')
objectArray.insert(4, 'i')
objectArray.insert(4, 'L')
objectArray.insert(4, 'w')
objectArray.insert(4, 'x')
objectArray.insert(4, 'T')
objectArray.insert(4, 'y')
objectArray.debug_print()
objectArray.delete(6)
objectArray.debug_print()
objectArray.delete(10)
objectArray.debug_print()
objectArray.delete(11)
objectArray.debug_print()
objectArray.delete(7)
objectArray.debug_print()
objectArray.delete(13)
objectArray.debug_print()
objectArray.swap(1,3)
objectArray.swap(7,8)
objectArray.debug_print()

